### ISSUE TITLE
Does not use localized decimal separator

### ISSUE THREAD

**Issue by Vages** [arve0/uubw#5]
UBW behaves a bit strangely when it comes to commas: It allows the user to use _only_ their in preferred locale's decimal separator. So for example, it allows you to use _only_ commas when preferring Norwegian bokmål (nb) as your preferred locale, and to the contrary, only a full stop when in English (en). 

We should take this into account when filling out the boxes; otherwise users might lose half hours here and there.

**Comment by arve0** [comment]
Will release tomorrow, do not have access to signing keys on this machine.
